# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/jasmine_sprout/setup-makefiles.py

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/jasmine_sprout

PRODUCT_COPY_FILES += \
    vendor/xiaomi/jasmine_sprout/proprietary/vendor/etc/MIUI_DualCamera_watermark.png:$(TARGET_COPY_OUT_VENDOR)/etc/MIUI_DualCamera_watermark.png

PRODUCT_PACKAGES += \
    com.fingerprints.extension@1.0.vendor \
    libgf_ca \
    libgf_hal \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libvendor.goodix.hardware.fingerprint@1.0
